### ISSUE TITLE
Code: 2902; Message: Can't stop ranging without permissions. Either BLUETOOTH or BLUETOOTH_ADMIN permission is not granted

### ISSUE THREAD

**Issue by j-s-a-m** [conichiGMBH/conichi-android-sdk#9]
Our app crashes on devices with Android versions < 6 as soon as the user tries to enter the Smarthotel area.

This bug did not exist in SDK 2.10.2. 

But with SDK 2.11.0-beta1 and 2.11.0-rc1 it always crashes. The problem is that we cannot revert to 2.10.2 because that version doesn't contain the changes for Android Oreo.

We had this problem or a similar problem in a sooner SDK, so this seems to be a regression bug.

Please provide an SDK release with all bugs fixed.

> SDK version: 2.11.0-beta1 and 2.11.0-rc1

> Environment: production

> Stacktrace
Package: com.hrs.b2c.android
Version Code: 8030001
Version Name: 8.3.0
Android: 4.4.2
Android Build: CHM-UL00 V100R001C00B261
Manufacturer: HUAWEI
Model: CHM-UL00
Thread: main-1
CrashReporter Key: 8EC5FA54-C28A-0FFD-4E19-14534566B5D797A9EEFA
Start Date: Tue Nov 21 08:34:25 CET 2017
Date: Tue Nov 21 08:52:10 CET 2017

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hrs.b2c.android/com.hrs.android.conichi.settings.ConichiSettingsActivity}: Code: 2902; Message: Can't stop ranging without permissions. Either BLUETOOTH or BLUETOOTH_ADMIN permission is not granted 
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2281)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2331)
	at android.app.ActivityThread.access$1000(ActivityThread.java:143)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1244)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5291)
	at java.lang.reflect.Method.invokeNative(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
	at dalvik.system.NativeStart.main(NativeStart.java)
Caused by: Code: 2902; Message: Can't stop ranging without permissions. Either BLUETOOTH or BLUETOOTH_ADMIN permission is not granted 
	at ao.stopRanging(ao.java:52)
	at com.conichi.sdk.CNISDK.stopScanningAndLeaveRegion(CNISDK.java:126)
	at com.conichi.sdk.CNISDK.setIncognitoModeOn(CNISDK.java:321)
	at com.hrs.android.conichi.wrapper.ConichiWrapper.setIncognitoMode(ConichiWrapper.java:297)

> Steps to reproduce
Enter the Smarthotel screen.

> Expected behavior
Do not crash, on all Android versions.

> Actual behavior
It crashes on Android versions < 6

**Comment by Ch3D** [comment]
Fixed in `2.11.0-rc2`
https://github.com/conichiGMBH/android-sdk/commit/4130959f6e615e19c0e7078264f228eff1fc2529
